### ISSUE TITLE
FT200 firmware with organization ID & name

### ISSUE THREAD

**Issue by tungree** [Flagtronics/Release#6]
FDM v1.15.0.0 or higher while checking for OTA update of FT200 devices will recursively look for FT200 firmware inside folder `firmware\ft200\v1\fw` (and all its sub-folders) of **Release** repository. Those firmware whose name following this pattern will be checked for OTA (others will be ignored):

```
flagging_<orgID>_<orgName>.bin
```

+ `<orgID>`: this must exactly match with the organization ID of the relevant firmware. **Organization ID of 0 is reserved for generic firmware**, which can be used by FDM software to update FT200 devices without organization ID or with unknown organization ID.

+ `<orgName>`: Arbitrary string (spaces, underscores, dashes, etc. are allowed).

Examples: `flagging_0_Generic FT200.bin`, `flagging_1_Organization A.bin`, `flagging_2_Organization B.bin`, etc.

@vtjballeng, could you build FT200 firmware with organization information as above and push them onto `main` branch? For your reference, you can find an example in [ft200_org](https://github.com/Flagtronics/Release/tree/ft200_org/firmware/ft200/v1/fw) branch.

**Comment by vtjballeng** [comment]
@tungree , I updated the repo with this method as we still need version to track org rule variations independent of the fw version:

`flagging_<orgID.orgVersion>_<orgName>.bin`

Most orgs have yearly rule changes.

If this formatting works for you then I please create a PR for that branch and I will merge it.

**Comment by tungree** [comment]
@vtjballeng, that format (`flagging_<orgID.orgVersion>_<orgName>.bin`) works for me. For now, FDMsw just ignores the org version.

Checking the new firmware you just pushed onto [ft200_org](https://github.com/Flagtronics/Release/tree/ft200_org/firmware/ft200/v1/fw) branch, I see that they don't have the org information in `readme.txt`. For example, this is `readme.txt` file using `flagging_2.0_PMH.bin` firmware:

![image](https://github.com/Flagtronics/Release/assets/11918762/71607c03-191f-46f2-9110-4e056545b6b0)

Could you please build those firmware files again with the org information embedded? A valid org-based FT200 firmware should have `readme.txt` like this:

![image](https://github.com/Flagtronics/Release/assets/11918762/9a88827f-ac70-4fea-9bb4-ae1b1e356099)

**Comment by vtjballeng** [comment]
Ah, good catch! Yes I will recompile those tomorrow @tungree .
