### ISSUE TITLE
Updated CAN Bus documentation?

### ISSUE THREAD

**Issue by collieking** [Flagtronics/Release#8]
I have a team owner that is running 8 cars at SCCA Runoffs and says the CAN Bus documentation on our Downloads page is not what he needs to program his AIM dashes. Is there an updated version of the documentation?

**Comment by vtjballeng** [comment]
The codes he needed were in the online documentation.

**Comment by collieking** [comment]
Yes, the customer figured it out and we closed this issue 2 days ago.
